_commit: 8f1cc90
_src_path: gh:bswck/skeleton
author_full_name: Bartosz Sławecki
author_username: bswck
docs: true
email_address: bswck.dev@gmail.com
github_username: bswck
license_name: MIT
package_name: copydocs
project_description: 'DRY: Reuse your docstrings.'
publish_on_pypi: true
pypi_project_description: 'DRY: Reuse your docstrings.'
pypi_project_name: copydocs
python_version: '3.8'
repo_name: copydocs
test_suite: true
use_precommit: true
visibility: public
